actions
cartoonsContactsIn: anAddressBook

	anAddressBook contacts add: (
	ABContact new
		firstName: 'Woody';
		lastName: 'Woodpecker';
		description: 'Woody Woodpecker is an anthropomorphic animated woodpecker[2] who appeared in theatrical short films produced by the Walter Lantz animation studio and distributed by Universal Pictures.[3] Though not the first of the screwball characters that became popular in the 1940s, Woody is one of the most indicative of the type.[4]';
		avatarId: 'woody-woodpecker.png';
		address: (
			ABAddress new
				city: 'Universal City';
				country: 'USA';
				telephone: (ABTelephone  new prefix: '1202'; number: '5550112'))).
				
	anAddressBook contacts add: (
	ABContact new
		firstName: 'Bugs';
		lastName: 'Bunny';
		description: 'Bugs Bunny is an animated cartoon character, created by the staff of Leon Schlesinger Productions (later Warner Bros. Cartoons) and voiced originally by the "Man of a Thousand Voices," Mel Blanc.[2] Bugs is best known for his starring roles in the Looney Tunes and Merrie Melodies series of animated short films, produced by Warner Bros. during the golden age of American animation. His popularity during this era led to his becoming an American cultural icon, as well as a corporate mascot of Warner Bros. Entertainment.[3]';
		avatarId: 'bugs-bunny.png';
		address: (
			ABAddress new
				city: 'Universal City';
				country: 'USA';
				telephone: (ABTelephone  new  prefix: '1202'; number: '5550146'))).
				
	anAddressBook contacts add: (
	ABContact new
		firstName: 'Daffy';
		lastName: 'Duck';
		description: 'Daffy Duck is an animated cartoon character produced by Warner Bros. Styled as an anthropomorphic black duck, the character has appeared in cartoon series such as Looney Tunes and Merrie Melodies, where he usually has been depicted as the best friend and occasional arch-rival of Bugs Bunny. Daffy was one of the first of the new "screwball" characters that emerged in the late 1930s to replace traditional everyman characters who were more popular earlier in the decade,[citation needed] such as Mickey Mouse and Popeye. Daffy starred in 133 shorts in the golden age, making him the third-most frequent character in the Looney Tunes/Merrie Melodies cartoons, behind Bugs Bunny''s 166 appearances and Porky Pig''s 159 appearances.';
		avatarId: 'daffy-duck.png';
		address: (
			ABAddress new
				city: 'Universal City';
				country: 'USA';
				telephone: (ABTelephone  new prefix: '1202'; number: '5550151'))).
				
				
	anAddressBook contacts add: (
	ABContact new
		firstName: 'Porky';
		lastName: 'Pig';
		description: 'Porky Pig is an animated cartoon character in the Warner Bros. Looney Tunes and Merrie Melodies series of cartoons. He was the first character created by the studio to draw audiences based on his star power, and the animators created many critically acclaimed shorts using the fat little pig. Even after he was supplanted by later characters, Porky continued to be popular with moviegoers and, more importantly, the Warners directors, who recast him in numerous everyman and sidekick roles.';
		avatarId: 'porky-pig.png';
		address: (
			ABAddress new
				city: 'Universal City';
				country: 'USA';
				telephone: (ABTelephone  new prefix: '1202'; number: '54321345'))).
				
	anAddressBook contacts add: (
	ABContact new
		firstName: 'Road';
		lastName: 'Runner';
		description: 'Road Runner was created by animation director Chuck Jones in 1948 for Warner Bros., while the template for their adventures was the work of writer Michael Maltese. The characters star in a long-running series of theatrical cartoon shorts (the first 16 of which were written by Maltese) and occasional made-for-television cartoons. It was originally meant to parody chase cartoons like Tom and Jerry, but became popular in its own right.';
		avatarId: 'road-runner.png';
		address: (
			ABAddress new
				city: 'Burbank';
				country: 'USA';
				telephone: (ABTelephone  new prefix: '1202'; number: '5550110'))).
				
	anAddressBook contacts add: (
	ABContact new
		firstName: 'Wile E.';
		lastName: 'Coyote';
		description: 'Wile E. Coyote (also known simply as "The Coyote") and The Road Runner are a duo of characters from the Looney Tunes and Merrie Melodies series of cartoons. In the cartoons, Coyote repeatedly attempts to catch and subsequently eat the Road Runner, a fast-running ground bird, but is never successful. Coyote, instead of his species'' animal instincts, uses absurdly complex contraptions (sometimes in the manner of Rube Goldberg) and elaborate plans to pursue his prey, which always comically backfire with Wile normally getting injured by the slapstick humor.';
		avatarId: 'wile-e-coyote.png';
		address: (
			ABAddress new
				city: 'Burbank';
				country: 'USA';
				telephone: (ABTelephone  new prefix: '1202'; number: '5550171'))).
			
		